name = "VPN Guru Theme"
license = "MIT"
licenselink = "https://github.com/yourusername/vpn-guru-theme/blob/master/LICENSE"
description = "Минималистичная светлая тема для блога о VPN"
homepage = "https://github.com/yourusername/vpn-guru-theme"
tags = ["blog", "minimal", "light", "responsive", "vpn"]
features = ["blog", "responsive", "minimal"]
min_version = "0.80.0"

[author]
  name = "VPN Guru Team"
  homepage = "https://security-master.github.io"

[original]
  name = "VPN Guru Theme"
  homepage = "https://security-master.github.io"
  repo = "https://github.com/yourusername/vpn-guru-theme"
